import type { Alert, Resource, Shelter, ActionStep, StateRisk } from './types'

export const stateRisks: StateRisk[] = [
    { name: 'Bihar', abbr: 'Bihar', riskLevel: 'critical', riskScore: 89, lat: 25.5, lng: 85.1, rainfall: 85, elevation: 12, population: 95, coastalDistance: 90 },
    { name: 'Assam', abbr: 'Assam', riskLevel: 'critical', riskScore: 85, lat: 26.2, lng: 92.9, rainfall: 90, elevation: 8, population: 70, coastalDistance: 70 },
    { name: 'Odisha', abbr: 'Odisha', riskLevel: 'critical', riskScore: 82, lat: 20.9, lng: 85.1, rainfall: 80, elevation: 10, population: 65, coastalDistance: 10 },
    { name: 'Jammu & Kashmir', abbr: 'J&K', riskLevel: 'high', riskScore: 72, lat: 33.7, lng: 76.9, rainfall: 60, elevation: 90, population: 30, coastalDistance: 95 },
    { name: 'West Bengal', abbr: 'WB', riskLevel: 'high', riskScore: 75, lat: 22.9, lng: 87.9, rainfall: 70, elevation: 5, population: 85, coastalDistance: 8 },
    { name: 'Uttar Pradesh', abbr: 'UP', riskLevel: 'high', riskScore: 68, lat: 26.9, lng: 80.9, rainfall: 55, elevation: 15, population: 98, coastalDistance: 85 },
    { name: 'Maharashtra', abbr: 'MH', riskLevel: 'high', riskScore: 70, lat: 19.7, lng: 75.7, rainfall: 65, elevation: 30, population: 90, coastalDistance: 5 },
    { name: 'Andhra Pradesh', abbr: 'AP', riskLevel: 'high', riskScore: 65, lat: 15.9, lng: 79.7, rainfall: 60, elevation: 20, population: 72, coastalDistance: 6 },
    { name: 'Jharkhand', abbr: 'JH', riskLevel: 'high', riskScore: 73, lat: 23.6, lng: 85.3, rainfall: 62, elevation: 35, population: 60, coastalDistance: 80 },
    { name: 'Uttarakhand', abbr: 'UK', riskLevel: 'medium', riskScore: 58, lat: 30.1, lng: 79.2, rainfall: 55, elevation: 85, population: 25, coastalDistance: 92 },
    { name: 'Himachal Pradesh', abbr: 'HP', riskLevel: 'medium', riskScore: 55, lat: 31.1, lng: 77.2, rainfall: 50, elevation: 88, population: 15, coastalDistance: 94 },
    { name: 'Madhya Pradesh', abbr: 'MP', riskLevel: 'medium', riskScore: 42, lat: 22.9, lng: 78.7, rainfall: 40, elevation: 40, population: 75, coastalDistance: 88 },
    { name: 'Telangana', abbr: 'TS', riskLevel: 'medium', riskScore: 50, lat: 17.1, lng: 79.0, rainfall: 48, elevation: 28, population: 65, coastalDistance: 75 },
    { name: 'Karnataka', abbr: 'KA', riskLevel: 'medium', riskScore: 38, lat: 15.3, lng: 75.7, rainfall: 45, elevation: 42, population: 60, coastalDistance: 15 },
    { name: 'Gujarat', abbr: 'GJ', riskLevel: 'medium', riskScore: 45, lat: 22.3, lng: 72.6, rainfall: 35, elevation: 18, population: 68, coastalDistance: 4 },
    { name: 'Chhattisgarh', abbr: 'CG', riskLevel: 'medium', riskScore: 44, lat: 21.3, lng: 81.9, rainfall: 42, elevation: 32, population: 52, coastalDistance: 82 },
    { name: 'Meghalaya', abbr: 'ML', riskLevel: 'medium', riskScore: 52, lat: 25.5, lng: 91.4, rainfall: 88, elevation: 60, population: 20, coastalDistance: 78 },
    { name: 'Punjab', abbr: 'PB', riskLevel: 'low', riskScore: 25, lat: 31.1, lng: 75.3, rainfall: 20, elevation: 22, population: 55, coastalDistance: 90 },
    { name: 'Rajasthan', abbr: 'RJ', riskLevel: 'low', riskScore: 20, lat: 27.0, lng: 74.2, rainfall: 10, elevation: 25, population: 58, coastalDistance: 92 },
    { name: 'Tamil Nadu', abbr: 'TN', riskLevel: 'medium', riskScore: 48, lat: 11.1, lng: 78.7, rainfall: 50, elevation: 15, population: 75, coastalDistance: 5 },
    { name: 'Kerala', abbr: 'KL', riskLevel: 'low', riskScore: 30, lat: 10.8, lng: 76.3, rainfall: 75, elevation: 35, population: 60, coastalDistance: 3 },
    { name: 'Goa', abbr: 'GA', riskLevel: 'low', riskScore: 22, lat: 15.3, lng: 74.1, rainfall: 70, elevation: 20, population: 18, coastalDistance: 2 },
    { name: 'Sikkim', abbr: 'SK', riskLevel: 'low', riskScore: 28, lat: 27.5, lng: 88.5, rainfall: 55, elevation: 92, population: 8, coastalDistance: 85 },
]

export const initialAlerts: Alert[] = [
    { id: '1', type: 'flood', title: 'Flood Warning', location: 'Bihar', detail: 'High Risk', time: '5 mins ago', severity: 'critical', read: false },
    { id: '2', type: 'evacuation', title: 'Evacuation Suggested', location: 'Odisha', detail: 'Zone 3', time: '23 mins ago', severity: 'high', read: false },
    { id: '3', type: 'resource', title: 'Resource Shortage', location: 'Maharashtra', detail: '', time: '1 hour ago', severity: 'medium', read: false },
    { id: '4', type: 'cyclone', title: 'Cyclone Alert', location: 'Tamil Nadu', detail: 'Category 2', time: '2 hours ago', severity: 'high', read: true },
    { id: '5', type: 'earthquake', title: 'Seismic Activity', location: 'J&K', detail: '4.2 Magnitude', time: '3 hours ago', severity: 'medium', read: true },
]

export const initialResources: Resource[] = [
    { name: 'Boats', icon: '⛵', current: 36, total: 50, unit: '' },
    { name: 'Ambulances', icon: '🚑', current: 22, total: 30, unit: '' },
    { name: 'Food Kits', icon: '📦', current: 410, total: 500, unit: '' },
    { name: 'Medical Teams', icon: '⚕️', current: 15, total: 20, unit: '' },
]

export const initialShelters: Shelter[] = [
    { name: 'Green Valley School', capacity: 1200, safety: 'Safe', distance: '2.3 km' },
    { name: 'City Hall Shelter', capacity: 800, safety: 'At Risk', distance: '5.1 km' },
    { name: 'Hilltop Complex', capacity: 1500, safety: 'Safe', distance: '7.8 km' },
    { name: 'Stadium Shelter', capacity: 3000, safety: 'Safe', distance: '12.4 km' },
    { name: 'Community Center', capacity: 600, safety: 'Full', distance: '3.2 km' },
]

export const initialActionPlan: ActionStep[] = [
    { id: 1, text: 'Deploy 12 Boats → Zone A', highlight: '12 Boats', completed: false },
    { id: 2, text: 'Open 3 Shelters in Zone B', highlight: '3 Shelters', completed: false },
    { id: 3, text: 'Send Alerts to 5 Districts', highlight: '5 Districts', completed: false },
]

export const translations: Record<string, Record<string, string>> = {
    en: {
        dashboard: 'Dashboard', riskEngine: 'Risk Engine', heatmap: 'Map',
        resources: 'Resources', shelters: 'Shelters', simulation: 'Simulation',
        alerts: 'Alerts', history: 'History', offlineMode: 'Offline Mode',
        settings: 'Settings', overallRiskScore: 'Overall Risk Score',
        decisionConfidence: 'Decision Confidence', goldenHourIndex: 'Golden Hour Index',
        safeZones: 'Safe Zones', highRiskZones: 'High Risk Zones', actNow: 'Act Now!',
        indiaRiskHeatmap: 'India Risk Map', quickAlerts: 'Quick Alerts',
        viewAll: 'View All', actionPlan: 'Action Plan (AI Generated)',
        executePlan: 'Execute Plan', resourceAllocation: 'Resource Allocation',
        autoOptimize: 'Auto-Optimize', shelterRecommendation: 'Shelter Recommendation',
        whatIfSimulation: 'What-If Simulation', riskProjection: 'Risk Projection',
        current: 'Current', after: 'After', systemStatus: 'System Status',
        allSystems: 'All Systems', operational: 'Operational',
        searchPlaceholder: 'Search Zone / Analyze…', commandCenter: 'Command Center',
        online: 'Online', offline: 'Offline', low: 'Low', medium: 'Medium',
        high: 'High', critical: 'Critical', shelterName: 'Shelter Name',
        capacity: 'Capacity', safety: 'Safety', distance: 'Distance',
        sendAlert: 'SOS', analyzeRisk: 'Analyze Risk', deploymentReady: 'Deployment Ready',
        whyThisRisk: 'Why This Risk?', exportData: 'Export',
    },
    hi: {
        dashboard: 'डैशबोर्ड', riskEngine: 'जोखिम इंजन', heatmap: 'मानचित्र',
        resources: 'संसाधन', shelters: 'आश्रय', simulation: 'सिमुलेशन',
        alerts: 'अलर्ट', history: 'इतिहास', offlineMode: 'ऑफ़लाइन मोड',
        settings: 'सेटिंग्स', overallRiskScore: 'समग्र जोखिम स्कोर',
        decisionConfidence: 'निर्णय विश्वास', goldenHourIndex: 'गोल्डन ऑवर',
        safeZones: 'सुरक्षित क्षेत्र', highRiskZones: 'उच्च जोखिम क्षेत्र',
        actNow: 'अभी कार्य करें!', indiaRiskHeatmap: 'भारत जोखिम मानचित्र',
        quickAlerts: 'त्वरित अलर्ट', viewAll: 'सभी देखें',
        actionPlan: 'कार्य योजना (AI)', executePlan: 'योजना क्रियान्वित करें',
        resourceAllocation: 'संसाधन आवंटन', autoOptimize: 'ऑटो-ऑप्टिमाइज़',
        shelterRecommendation: 'आश्रय सिफारिश', whatIfSimulation: 'क्या-अगर सिमुलेशन',
        riskProjection: 'जोखिम अनुमान', current: 'वर्तमान', after: 'बाद',
        systemStatus: 'सिस्टम स्थिति', allSystems: 'सभी सिस्टम', operational: 'चालू',
        searchPlaceholder: 'क्षेत्र खोजें…', commandCenter: 'कमांड सेंटर',
        online: 'ऑनलाइन', offline: 'ऑफ़लाइन', low: 'कम', medium: 'मध्यम',
        high: 'उच्च', critical: 'गंभीर', shelterName: 'आश्रय', capacity: 'क्षमता',
        safety: 'सुरक्षा', distance: 'दूरी', sendAlert: 'SOS',
        analyzeRisk: 'जोखिम विश्लेषण', deploymentReady: 'तैनाती तैयार',
        whyThisRisk: 'यह जोखिम क्यों?', exportData: 'निर्यात',
    },
    ta: {
        dashboard: 'டாஷ்போர்ட்', riskEngine: 'ஆபத்து இயந்திரம்', heatmap: 'வரைபடம்',
        resources: 'வளங்கள்', shelters: 'தங்குமிடங்கள்', simulation: 'உருவகப்படுத்தல்',
        alerts: 'எச்சரிக்கைகள்', history: 'வரலாறு', offlineMode: 'ஆஃப்லைன்',
        settings: 'அமைப்புகள்', overallRiskScore: 'மொத்த ஆபத்து மதிப்பெண்',
        decisionConfidence: 'நம்பிக்கை', goldenHourIndex: 'தங்க மணி நேரம்',
        safeZones: 'பாதுகாப்பான மண்டலங்கள்', highRiskZones: 'அதிக ஆபத்து மண்டலங்கள்',
        actNow: 'இப்போது நடவடிக்கை!', indiaRiskHeatmap: 'இந்தியா ஆபத்து வரைபடம்',
        quickAlerts: 'வேகமான எச்சரிக்கைகள்', viewAll: 'அனைத்தையும் பார்',
        actionPlan: 'நடவடிக்கை திட்டம் (AI)', executePlan: 'திட்டத்தை செயல்படுத்து',
        resourceAllocation: 'வளங்களின் ஒதுக்கீடு', autoOptimize: 'தானியங்கி மேம்படுத்தல்',
        shelterRecommendation: 'தங்குமிட பரிந்துரை', whatIfSimulation: 'என்ன-என்றால்',
        riskProjection: 'ஆபத்து அனுமானம்', current: 'தற்போதைய', after: 'பிறகு',
        systemStatus: 'அமைப்பு நிலை', allSystems: 'அனைத்து அமைப்புகள்', operational: 'செயல்பாட்டு',
        searchPlaceholder: 'மண்டலம் தேடவும்…', commandCenter: 'கட்டளை மையம்',
        online: 'ஆன்லைன்', offline: 'ஆஃப்லைன்', low: 'குறைந்த', medium: 'நடுத்தர',
        high: 'உயர்', critical: 'கடுமையான', shelterName: 'தங்குமிடம்', capacity: 'திறன்',
        safety: 'பாதுகாப்பு', distance: 'தூரம்', sendAlert: 'SOS',
        analyzeRisk: 'ஆபத்தை பகுப்பாய்வு', deploymentReady: 'தொடக்கத்திற்கு தயார்',
        whyThisRisk: 'ஏன் இந்த ஆபத்து?', exportData: 'ஏற்றுமதி',
    },
}
